/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AntesDepoisRouteImport } from './routes/antes-depois'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as JuridicoRouteImport } from './routes/juridico'
import { Route as SindicaturaRouteImport } from './routes/sindicatura'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AntesDepoisRoute = AntesDepoisRouteImport.update({
  id: '/antes-depois',
  path: '/antes-depois',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const JuridicoRoute = JuridicoRouteImport.update({
  id: '/juridico',
  path: '/juridico',
  getParentRoute: () => rootRouteImport,
} as any)
const SindicaturaRoute = SindicaturaRouteImport.update({
  id: '/sindicatura',
  path: '/sindicatura',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/antes-depois': typeof AntesDepoisRoute
  '/contato': typeof ContatoRoute
  '/equipe': typeof EquipeRoute
  '/juridico': typeof JuridicoRoute
  '/sindicatura': typeof SindicaturaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/antes-depois': typeof AntesDepoisRoute
  '/contato': typeof ContatoRoute
  '/equipe': typeof EquipeRoute
  '/juridico': typeof JuridicoRoute
  '/sindicatura': typeof SindicaturaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/antes-depois': typeof AntesDepoisRoute
  '/contato': typeof ContatoRoute
  '/equipe': typeof EquipeRoute
  '/juridico': typeof JuridicoRoute
  '/sindicatura': typeof SindicaturaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/antes-depois'
    | '/contato'
    | '/equipe'
    | '/juridico'
    | '/sindicatura'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/antes-depois'
    | '/contato'
    | '/equipe'
    | '/juridico'
    | '/sindicatura'
  id:
    | '__root__'
    | '/'
    | '/antes-depois'
    | '/contato'
    | '/equipe'
    | '/juridico'
    | '/sindicatura'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AntesDepoisRoute: typeof AntesDepoisRoute
  ContatoRoute: typeof ContatoRoute
  EquipeRoute: typeof EquipeRoute
  JuridicoRoute: typeof JuridicoRoute
  SindicaturaRoute: typeof SindicaturaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antes-depois': {
      id: '/antes-depois'
      path: '/antes-depois'
      fullPath: '/antes-depois'
      preLoaderRoute: typeof AntesDepoisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juridico': {
      id: '/juridico'
      path: '/juridico'
      fullPath: '/juridico'
      preLoaderRoute: typeof JuridicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sindicatura': {
      id: '/sindicatura'
      path: '/sindicatura'
      fullPath: '/sindicatura'
      preLoaderRoute: typeof SindicaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AntesDepoisRoute: AntesDepoisRoute,
  ContatoRoute: ContatoRoute,
  EquipeRoute: EquipeRoute,
  JuridicoRoute: JuridicoRoute,
  SindicaturaRoute: SindicaturaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
